const TermsAndConditions = () => {

    const divStyles = {
        // boxShadow: '1px 3px 5px #1C2833',
        margin: '2em',
        padding: '1em',
        background:'white',
        
    };
    return (
        <div class="policy">
        
        <div style={divStyles} >
            <h1>Terms And Conditions</h1>
            <p class="text" className="text-gray-900">
            This document is an electronic record in terms of Information Technology Act, 
            2000 and rules there under as applicable and the amended provisions pertaining to 
            electronic records in various statutes as amended by the Information Technology Act, 2000.
            This electronic record is generated by a computer system and does not require any physical
            or digital signatures.
            This document is published in accordance with the provisions of Rule 3 (1) of the Information
            Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and 
            regulations, privacy policy and Terms of Use for access or usage of EasyFarm website.
            The domain name EasyFarm (hereinafter referred to as "Website") is owned by 
            EasyFarm Internet Private Limited a company incorporated under the Companies Act, 1956 with
            its registered office at Vaishnavi Summit, Ground Floor, 7th Main, 80 feet Road, 3rd Block,
            Koramangala Industrial Layout, Next to Wipro office, Corporation Ward No. 68, Koramangala,
            Bangalore - 560 034, Karnataka, India (hereinafter referred to as "Flipkart").
            Your use of the Website and services and tools are governed by the following terms and
            conditions ("Terms of Use") as applicable to the Website including the applicable policies 
            which are incorporated herein by way of reference. If You transact on the Website, 
            You shall be subject to the policies that are applicable to the Website for such transaction.
            By mere use of the Website, You shall be contracting with EasyFarm Internet Private Limited and 
            these terms and conditions including the policies constitute Your binding obligations, with 
            EasyFarm.

.<br /><br />

            <h5>Your Account and Registration Obligations</h5>

            If You use the Website, You shall be responsible for maintaining the confidentiality of your
            Display Name and Password and You shall be responsible for all activities that occur under 
            your Display Name and Password. You agree that if You provide any information that is untrue,
            inaccurate, not current or incomplete or We have reasonable grounds to suspect that such 
            information is untrue, inaccurate, not current or incomplete, or not in accordance with the
            this Terms of Use, We shall have the right to indefinitely suspend or terminate or block 
            access of your membership on the Website and refuse to provide You with access to the Website.
<br /><br />
            <h5>Communications</h5>

            When You use the Website or send emails or other data, information or communication to us, 
            You agree and understand that You are communicating with Us through electronic records and 
            You consent to receive communications via electronic records from Us periodically and as and
            when required. We may communicate with you by email or by such other mode of communication, 
            electronic or otherwise.


            </p>
            
        </div>
    </div>

        )
    }
    export default TermsAndConditions