//import o3 from "./o3.png";
//import p9 from "./p9.png";
export const products = [
    {
      id: 1,
      title: "product 1",
      description: "farming tools",
      price: "2500",
      img:"https://cdn.moglix.com/p/ymfU7GYmmvE5a-xxlarge.jpg",
      quantity: 1,
    },
    {
      id: 2,
      title: "product 2",
      description: "farming tools",
      price: "2300",
      img: "https://cdn.moglix.com/p/q18E092n8WMT9-xxlarge.jpg",
      quantity: 1,
    },
    {
      id: 3,
      title: "product 3",
      description: "farming tools",
      price: "3500",
      img: "https://cdn.moglix.com/p/I/O/S/d/MINIOSLY5DF81-xxlarge.jpg",
      quantity: 1,
    },
    {
      id: 4,
      title: "product 4",
      description: "farming tools",
      price: "90500",
      img: "https://cdn.moglix.com/p/I/9/E/d/MINI9EE35DGNF-xxlarge.jpg",
      quantity: 1,
    },
    {
      id: 5,
      title: "product 5",
      description: "farming tools",
      price: "2500",
      img: "https://cdn.moglix.com/p/TttS74xfA7AGV-xxlarge.jpg",
      quantity: 1,
    },
    {
      id: 6,
      title: "product 6",
      description: "farming tools",
      price: "3500",
      img: "https://cdn.moglix.com/p/rDkZu9Ex3Ad7W-xxlarge.jpg",
      quantity: 1,
    },
    {
      id: 7,
      title: "product 7",
      description: "farming tools",
      price: "2500",
      img: "https://cdn.moglix.com/p/NOosT7WvbYSD0-xxlarge.png",
      quantity: 1,
    },
    {
      id: 8,
      title: "product 8",
      description: "farming tools",
      price: "90500",
      img: "https://cdn.moglix.com/p/ymfU7GYmmvE5a-xxlarge.jpg",
      quantity: 1,
    },
    {
      id: 9,
      title: "product 9",
      description: "farming tools",
      price: "2500",
      img: "https://cdn.moglix.com/p/q18E092n8WMT9-xxlarge.jpg",
      quantity: 1,
    },
  ];
  